apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-nodejs-crt
spec:
  secretName: example-nodejs-crt
  dnsNames:
  - example-nodejs.revolgy.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - example-nodejs.revolgy.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
